### ISSUE TITLE
Using Java code completion with Java 8.

### ISSUE THREAD

**Issue by splinc** [bobbylight/RSTALanguageSupport#20]
I am trying to use Java language support with RSyntaxTextArea in an application compiled using Java 8. Initial attempts resulted in some exceptions being thrown. Specifically there were exceptions being thrown for "Unknown tag for constant pool info" and warnings about parsing signatures (because of double colons :: in some signatures). I made some quick local changes to add support for the missing ConstantPoolInfo tags and changing the parsing in Signature#getClassParamTypes() to skip over double colons and this seems to allow the code completion to work nicely (at least so far!). It seems that it would be relatively easy to improve compatibility with Java 8. However, I'm not an expert in the details of the Java language specification or byte code model (and would prefer not to be!) and I'm sure there are other further implications of these changes that would need to be addressed to make the library stable. I can make my local changes available as a pull request if this is of interest. I am more interested in the code completion aspects than error parsing at this stage.

**Comment by bobbylight** [comment]
Hi @splinc,

I could take a stab at these changes myself, but if you already have them, could you make them available as a pull request?

And/or provide an example of how you got an error about signatures with double colons?

It's been a *very* long time since I worked on the Java code completion, but I'd like to clean it up to at least not have obvious problems with Java 8.

**Comment by bobbylight** [comment]
See #23; this will be addressed soon.

**Comment by bobbylight** [comment]
Fixed by merging pull request #23.
