### ISSUE TITLE
Library vulnerabilities

### ISSUE THREAD

**Issue by pavel-shelentsov** [bobbylight/RSTALanguageSupport#43]
Hello, 
We use `languagesupport` artifact in our project, and after sources analysis using static veracode analyzer we have found some vulnerabilities.

Please have a look at attached report [languagesupport_2.6.pdf](https://github.com/bobbylight/RSTALanguageSupport/files/1672615/languagesupport_2.6.pdf) to recognize is this real vulnerabilities or an false positive alerts.

**Comment by bobbylight** [comment]
Although I'm sure this is too late, here's my take.  If you have specific concerns or items you'd want fixed, please open individual tickets for them.

* All of the CWE ID 73 issues (Exernal Control of File Name or Path) are invalid since this is a library for client-side applications, not webapps, and the _intent_ is to allow users to access files on the local file system, not to restrict them to a sandbox.
* CWE ID 611 issues (Improper Restriction of XML External Entity Reference) are false positives for the same reason - this library is for client-side apps and we don't restrict what user input can be.
* CWE ID 829 (Inclusion of Functionality from Untrusted Control Sphere) could be considered a false positive as long as you don't deploy the `DemoApplet` class as an applet, which I assume you don't.  Admittedly it's annoying for this to show up in a security scan, so if you want this addressed, please open a separate ticket to have any demo classes such as this one moved to a separate submodule in the project; that way they won't be included in a build of the library proper.
* Improper Resource Shutdown or Release (CWE ID 404) - Like the item above, this is an issue found in the demo application.  Please open a separate ticket if you want this code moved to a separate submodule in this gradle project.
